96boards/website

- 96boards.org/Projects/AOSPTVHikey/README.md
Project Readme added
Signed-off-by: Sahaj Sarup <sahajsarup@gmail.com>
> AOSPTV Hikey Initial Commit

- _projects/view/96Brews/README.md
- _projects/view/BraceYourself/README.md
- _projects/view/ComuniCibo/README.md
- _projects/view/Docker96BoardsCE/README.md
- _projects/view/DragonDetector/README.md
- _projects/view/Mosquitto/README.md
- _projects/view/PassMe/README.md
- _projects/view/ProjectBIGButton/README.md
- _projects/view/SAM/README.md
- _projects/view/SmartBoiler/README.md
- _projects/view/SuperParking/README.md
Broken images on the projects readme fixed.
> Projects broken images fix

- _data/product_db.yaml
Signed-off-by Shovan Sargunam shovan@linaro.org
> updated database with correct links

- _posts/2015/2015-07-30-helping-makers-create-exciting-new-technologies-dragonboard-410c.md
- _posts/2017/2017-07-05-google-assistant-96boards-instructions.md
- _product/accessories/accessories.html
- _product/accessories/adapter/README.md
- _product/accessories/debug/README.md
- _product/accessories/power/README.md
- _product/ce/bubblegum-96/README.md
- _product/ce/ce.html
- _product/ce/dragonboard410c/README.md
- _product/ce/hiKey/README.md
- _product/ce/mediatek-x20/README.md
- _product/ee/ee.html
- _product/ie/ie.html
- _product/mezzanine/linkspritesensorkit/README.md
- _product/mezzanine/mezzanine.html
- _product/mezzanine/sensors-mezzanine/README.md
- _product/mezzanine/stm32/README.md
- _product/mezzanine/uartserial/README.md
Updated correct URL links
Removed capitalisation 
Updated Images
Lazy load images
> URL updates & Redirects

- _data/product_db.yaml
> updated product db

- _data/product_db.yaml
- Added Nitrogen buy link
- Updated Carbon buy short link
> Udated db with nitrogen

- _product/ie/nitrogen/README.md
> Added Nitrogen table with additional spec information

- help/blog.md
Updated Blog help documentation in the /help folder.
> Help Documentation

- _posts/2017/2017-07-13-path-libmraa-96boards-part-3.md
> Blog: Path to libmraa Part-3 

- _posts/README.md
First pass at adding some sort of instructions/links to within the 
_posts folder.
> Added readme with links

- README.md
- digest/README.md
Fixed relative link on top page and added most recent digest links for digest 16,17 and 18
> Small changes and additions to top page and digest

- _data/product_db.yaml
- _posts/2017/2017-07-13-path-libmraa-96boards-part-3.md
- _product/mezzanine/sensors-mezzanine/README.md
- blog/index.html
- blog/tag.html
- help/YYYY-MM-DD-new-template.md
- search/README.md
Fixed some broken documentation links in the product_db.yml database.
> Few changes to website content

- _product/mezzanine/sensorkey/README.md
> Added links down DL and view SensorKey schematics

- _posts/2017/07/2017-07-25-vulkan-hikey960.md
- help/blog.md
Changed the youtube links to youtube/embed links for the Iframe media.html include.
> Added update to Vulcan Blog Post

- _product/ie/nitrogen/README.md
> Fixed nitrogen description (first attempt)

- _product/ie/nitrogen/README.md
> Changed description to nitrogen board

- _product/ie/nitrogen/README.md
> Fixed front matter with new description

- _projects/index.html
Changed the iterator increment to {% increment iterator %} - fixed error on building site.
> Fixed iterator variable error

- _projects/index.html
{% increment iterator %} was outputing a range of numbers for each project row. Going back to old method for now.
> Updated the projects page to fix miscellaneous output of range.

- _data/redirects.csv
Added a new file, redirects.csv, as part of the automation building to set up redirects on S3.
> Initial redirects.csv file (for testing)

- openhours/README.md
> Added OpenHours content for Ep 65

- openhours/README.md
> Changed episode description from ep 64 to ep 66

- digest/README.md
> Added issues 21 and 22 to digest page

- _posts/2017/08/2017-08-03-openhours-ep64-blackwhale.md
- _posts/2017/08/2017-08-10-openhours-ep65-fedora-on-96boards.md
- openhours/README.md
- Changed the description to match contents for Openhours episode 66.
- Changed out the calendar links for this week's episode (Aug 17th).
- Added blog for OpenHours episode 64
- Added blog for OpenHours episode 65
> Changed description to OpenHours ep 66

- go/sfo17-connect-reach/README.md
> Added go page for external invitation to sfo16 connect

- _posts/2017/08/2017-08-17-openhours-ep66-monero-kovri-96boards.md
- digest/README.md
- go/README.md
- go/sfo17-connect-reach/README.md
> Fixed some description and replaced some occ or SF with Burlingame

- go/sfo17-connect-reach/README.md
- verticals/README.md
Iframe height & Front matter for Verticals
> iFrame height & front matter

- _projects/projects.md
> Removed permalink from non website rendered page

- _data/product_db.yaml
- _data/redirects.csv
> Added redirects for newsletter/digest page - updated NeonKey Schematics link

- _posts/2017/09/2017-09-13-open-source-summit-2017.md
- openhours/README.md
> Edited OpenHours for episode 72

- openhours/README.md
> Modified calendar and description for ep 73

- openhours/README.md
> Changed description to episode 74, changed calendar links

- _product/mezzanine/neonkey/README.md
> Fix Neonkey product page

- _posts/2017/08/2017-08-24-openhours-ep67-live-from-denver.md
- _posts/2017/08/2017-08-31-openhours-ep68-tech-talk.md
- _posts/2017/09/2017-09-07-openhours-ep69-dragonboard-linaro-team.md
- _posts/2017/09/2017-09-14-openhours-ep70-project-cycle.md
- _posts/2017/09/2017-09-21-openhours-ep71-aws-greengrass.md
- _posts/2017/09/2017-09-28-openhours-ep72-live-linaro-connect-sfo-2017.md
- _posts/2017/10/2017-10-05-openhours-ep73-safe2med.md
- _posts/2017/10/2017-10-12-openhours-ep74-dragonwally.md
Added blogs for OpenHours episodes 67-73, all individually committed.
> Added 8 new OpenHours blogs

- openhours/README.md
> New OpenHours ep 75 description and calendar links

- openhours/README.md
> Updated description and calendar link for OpenHours ep 76

- _posts/2015/12/2015-12-23-reference-software-platform-15-12-release.md
- _posts/2016/08/2016-08-19-96boards-openhours-14-recap.md
- _posts/2017/01/2017-01-06-welcome-2017-year-96boards.md
- _posts/2017/04/2017-04-20-openhours-community-minute-testing-96boards-audio-mezzanine-jean-marc-jobin.md
- _posts/2017/10/2017-10-12-openhours-ep74-dragonwally.md
- go/db410c-partnership-brazil/README.md
@shovanuk These should be the final broken links.
> Broken link fixes.

- _data/redirects.csv
> Removed incorrect redirect

- _data/redirects.csv
- _product/mezzanine/README.md
> Missing redirects and removed unwanted front matter

- _posts/2017/10/2017-10-19-openhours-ep75-one-rf.md
- _posts/2017/10/2017-10-26-openhours-ep76-deep-learning.md
- openhours/README.md
openhours: Updated calendar link and adjusted description with episode 77 place holder
posts_/2017/10: Added two new blogs for OpenHours episode 75 and 76 summaries
> openhours: / posts_/2017/10: Updates and additions

- _data/product_db.yaml
- contact/README.md
> Changed /contact/ form to a Cognito form - updated wrong search term.

- openhours/README.md
> openhours: Added description for OpenHours ep 77

- _posts/2017/09/2017-09-19-self-balancing-bot-using-96boards-part2.md
- _posts/2017/11/2017-11-01-self-balancing-bot-using-96boards-part3.md
This commit adds the self balancing bot final revision blog and modifies the title of
the previous blog.
> blog: add self balancing bot final blog

- _posts/2017/08/2017-08-04-introducing-self-balancing-bot-using-96boards.md
- _posts/2017/08/2017-08-11-self-balancing-bot-using-96boards-part1.md
- _posts/2017/09/2017-09-19-self-balancing-bot-using-96boards-part2.md
> blog: Self Balancing Bot: Fix broken links

- openhours/README.md
> Added new calendar link and ep 78 description for OH

- openhours/README.md
> update openhours page for episode 79: Timesys

- _posts/2017/11/2017-11-14-agl-on-dragonboard410c-part2.md
> blog: add AGL on Dragonboard410c Part-2

- openhours/README.md
> Added description for episode 80. Disclaimer for Thanksgiving episode

- help/YYYY-MM-DD-new-template.md
> Added Image Dimensions to Blog Template

- openhours/README.md
Added new calendar link
Added new description
> openhours: updates for ep 81

- _posts/2017/12/2017-12-04-getting-started-with-the-secure96-tpm.md
+ Added related links
+ Added <sub><sub>
+ Edited front matter
> Enhanced the post by adding video & linking

- _posts/2017/12/2017-12-04-getting-started-with-the-secure96-tpm.md
> Updated secure96 blog post to fix render issue

- _data/members_db.yaml
> Removed Long Sung and LeMaker from 96boards member db

- _projects/submit-new.md
> Added Temporary Page for Project Submission.

- go/96boards-india-initiative/README.md
> go: Add go page for 96Boards India initiative

- go/README.md
> Add link to 96Boards India Initiative

- openhours/README.md
> openhours: Updated episode description and calendar link

- go/96boards-india-initiative/README.md
> Add links to social media

- openhours/README.md
Updated calendar link and episode description
> openhours/README.md: Updated for episode #83

- _posts/2017/12/2017-12-19-media-server-revisited.md
> blog: media_server: add credits

- openhours/README.md
> openhours: update for calendar link and episode description

- _posts/2017/12/2017-12-23-openhours-ep83-holiday.md
> posts/2017/12: Added OpenHours ep 83 holiday blog

- _posts/2017/12/2017-12-29-patient-monitoring-system-part1.md
> blog: Add Patient Monitoring System Part 1

- _posts/2018/01/2018-01-01-welcome-2018.md
- openhours/README.md
> openhours: Updated calendar link and ep 85 description

- openhours/README.md
Description for episode 87 will need to updated
one more time to reflect this week's episode
description. Right now the update is just a place
holder.
> openhours: Changed calendar invite and description.

- openhours/README.md
Sahaj will demo the Carbon Rover and Mani will
demo his most recent work with his patience
monitoring system.
> openhours: added description for episode 87.

- _posts/2018/01/2018-01-12-patient-monitoring-system-part2.md
blog not showing up on the home page probably because of the wrong date
> correct date for Part 2 Patient Monitoring System

- _data/product_db.yaml
- _data/redirects.csv
- _posts/2017/10/2017-10-24-basic-threads-zephyr.md
IoTEdition -> iot
requesting review:
@sdrobertw 
@shovanuk
> modify links related IoTEdition documentation

- _posts/2018/01/2018-01-31-patient-monitoring-system-part4.md
Add the final blog of the Patient Monitoring System using 96Boards
blog series.
> Add Patient Monitoring System using 96Boards Part 4 blog

- openhours/README.md
> openhours: Added new OpenHours description for ep 89

- _posts/2018/02/2018-02-02-poplar-pcie.md
> correct image file extension

- _posts/2018/02/2018-02-09-ece191-ucsd-fourweeksummary.md
- openhours/README.md
> openhours: Updated description for episode 90

- _posts/2018/02/2018-02-09-ece191-ucsd-fourweeksummary.md
> posts/2018/02: Fixed 4 Weeks summary blog from ECE 191 students.

- _data/news.yaml
> data/news: Added news on Arrow at Embedded World

- _posts/2018/02/2018-02-08-openhours-ep90-the-cello.md
> posts/2018/02: Added blog for OpenHours ep 90

- _data/routingrules.json
Corrected the redirect for the HiKey user manual.
> Fix user manual redirect

- _posts/2018/02/2018-02-08-openhours-ep90-the-cello.md
> posts/2018/02/openhours90: Small format fix to chat log

- _product/ce/dragonboard820c/README.md
> product/DB820c: Small change to description

- _posts/2018/01/2018-01-01-welcome-2018.md
- _product/ce/dragonboard820c/README.md
> consumer/db820c: Small description fix

- _data/members_db.yaml
- _posts/2016/11/2016-11-02-diy-drone-featuring-gumstix-96boards-take-flight-openhours.md
> Added LeMaker to Manufacturing Partners

- _posts/2018/02/2018-02-23-photobooth-part1.md
Add 96Boards Photobooth Part 1 blog along with Video demonstration
> blog: Add Part 1 of 96Boards Photobooth

- _posts/2015/12/2015-12-16-servo-motor-control.md
- _posts/2017/07/2017-07-29-boot-linux-from-sd-card-uboot.md
- go/2018-partnership-brazil/README.md
- go/db410c-partnership-brazil/README.md
- go/hackathon-mexico/README.md
- openhours/README.md
> openhours: Changes description to episode 93

- openhours/README.md
> OH ep 95 description update

- openhours/README.md
> OH ep 95 description update - 2

- _data/product_db.yaml
> data/product_db.yaml: Removed support link for forums until launched

- _data/product_db.yaml
> Revert "data/product_db.yaml: Removed support link for forums until launched"

- _data/product_db.yaml
> data/product_db.yaml: Removed broken link

- openhours/README.md
> openhours: Description change to episode 96

- openhours/README.md
> openhours: Changed description for OpenHours

- openhours/README.md
> oh episode 97 description updated

- _data/product_db.yaml
> data/product_db.yaml: Removed tabs for initial build to fix link issues

- _product/ce/rock960/README.md
> product/ce/rock960: Changed occurance of Ultra96 to Rock960

- _data/product_db.yaml
- openhours/README.md
> data/product_db.yaml: Added sub tabs and links to OSs for Rock960

- openhours/README.md
> oh: desc update ep 99

- _data/product_db.yaml
> ultra96: Added opensuse as third party images

- _posts/2018/04/2018-04-13-path-libmraa-96boards-part-7.md
> blog: Add Our Path to Libmraa with 96Boards - Part 7

- openhours/README.md
> oh: update for episode 100

- go/README.md
- go/wistem-2018/README.md
- Added WISTEM go page to the lineup
- Added relative link to WISTEM go page to top level README.md
> go: Added wiSTEM go page and link to README.md

- go/wistem-2018/README.md
> go/wistem-2018: Made a bunch of edits and added more content

- go/wistem-2018/README.md
> go/wistem-2018: Typo fix

- _product/mezzanine/mipiadapter/README.md
Update the link of the store in the product page. The previous link has been invalid.
> Change the link of the store

- _product/mezzanine/shiratech-lte/README.md
> product/mezzanine: Added link to product brief

- _data/product_db.yaml
> data/product_db.yaml: Attempt to fix rendering issue on website

- _posts/2015/11/2015-11-06-xenomai-on-the-96boards.md
> Attempt to fix broken link for website build

- _posts/2018/05/2018-05-01-wistem-01.md
> Added final formating for first WISTEM blog

- _posts/2018/05/2018-05-03-wistem-03.md
- go/wistem-2018/README.md
- Added a new segment to the lineup for live stream interviews to go page
- Added interview 3 to blog section
> Added interview 3 to blogs section and made small change to WISTEM page

- _posts/2018/05/2018-05-03-wistem-03.md
> Attempt to fix build for interview 3 from WISTEM initiative

- _posts/2018/05/2018-05-03-wistem-03.md
> Small change to interview 3 WISTEM to trigger build

- _data/product_db.yaml
- _posts/2018/05/2018-05-03-wistem-03.md
- _product/mezzanine/secure96/README.md
> Fixed purchase link for Secure96

- go/wistem-2018/README.md
Interview with Lindey the_engineeress
> go/wistem-2018: Added link to video for video interview 1

- openhours/README.md
> openhours: Changed description for week 2 of WISTEM month

- _posts/2018/05/2018-05-04-wistem-04.md
> Typo fix in wistem interview 4

- _posts/2018/04/2018-04-18-bloom-box-part-1.md
Got rid of ">" symbols. Have been bothering me for weeks
> Removed unnecessary symbols

- _posts/2018/05/2018-05-08-magic-mirror-part-2.md
> blog: magic mirror pt 2

- _posts/2018/05/2018-05-05-wistem-05.md
- _posts/2018/05/2018-05-07-wistem-05.md
- _posts/2018/05/2018-05-08-wistem-06.md
> Changed date for interview 5 and added interview 6

- _posts/2018/05/2018-05-08-wistem-06.md
> posts/2018/05: Fix small typo in interview 6

- _posts/2018/01/2018-01-12-patient-monitoring-system-part2.md
- _posts/2018/05/2018-05-09-wistem-07.md
> posts/2018/05: Added interview 7 for WISTEM initiative

- _posts/2018/05/2018-05-10-wistem-08.md
> posts/2018/05: Added interview 8 for WISTEM initiative

- _posts/2018/05/2018-05-10-wistem-08.md
> posts/2018/05: Small addition to previous interviews section

- _product/ce/bubblegum-96/README.md
Add onboard PMU and button info for Bubblegum-96 board
> ce: bubblegum-96: Add PMU and Button info

- _posts/2018/05/2018-05-11-96boards-gps-mezz-firstborn.md
> post/2018/05: Small change to a title

- _product/ce/hikey970/README.md
> consumer/hikey970: Added board landing page and yaml data

- _data/news.yaml
- _product/ce/hikey970/README.md
> ce/hikey970: Added some media news and coming soon tags for OS

- _posts/2018/05/2018-05-14-wistem-10.md
> posts: Added interview 10 from WISTEM initiative

- _posts/2018/05/2018-05-14-wistem-10.md
> posts/2018/05: Attempt to fix broken links

- _posts/2018/05/2018-05-11-96boards-gps-mezz-firstborn.md
Post with Groupgets, QWERTY and 96Boards
> posts/2018/05: Grammar punctuation and links to mezzanine post

- openhours/README.md
> openhours: Added description for livestream 3 with Falkyou

- openhours/README.md
> openhours: Adding link to Falkyou instagram

- _posts/2018/05/2018-05-16-wistem-12.md
> posts/2018/05: Added interview 12 for WISTEM

- _posts/2018/05/2018-05-16-wistem-12.md
> posts/2018/05: Changed date for interview 11 WISTEM

- _product/ce/hikey960/README.md
> ce/hikey960: Updated purchase link for Hikey960

- _posts/2018/05/2018-05-21-wistem-13.md
> posts/2018/05: Added interview 13 to lineup

- go/wistem-2018/README.md
- openhours/README.md
> Updated OpenHours and go pages with current information

- _data/news.yaml
- _posts/2017/01/2017-01-06-welcome-2017-year-96boards.md
> Attempt to fix broken links for website build

- _posts/2018/05/2018-05-21-wistem-13.md
- go/wistem-2018/README.md
- Added latest blog to go page
- Fixed spelling of silli_scientist
- Fixed formatting on latest interview blog
> Several changes for WISTEM initiative

- openhours/README.md
> openhours: attempt to fix formatting for multiple countdowns

- openhours/README.md
> openhours: Added description to openhours site for week4

- openhours/README.md
> Small change to kick off website build

- _posts/2018/01/2018-01-01-welcome-2018.md
> removed broken links

- _product/ie/bpi96/README.md
> Small change, attempt to fix broken links

- _product/ie/bpi96/README.md
> products/ie/bpi96: Attempt to fix broken links

- _product/ie/4iot/README.md
> product/ie/4iot: Attempt to publish landing page

- _posts/2018/05/2018-05-28-wistem-14.md
> small change to date in wistem post 14

- openhours/README.md
Livestream 6 will be with Estefannie from Estefannie
Explains it all.
> openhours: changed description for wistem livestream 6

- go/wistem-2018/README.md
> go/wistem-2018: Added calendar link for Estefannie livestream

- _posts/2018/05/2018-05-28-wistem-14.md
> Small change to trigger build

- _posts/2018/05/2018-05-29-wistem-15.md
- openhours/README.md
> Slowly winding down from WISTEM and back to OpenHours content

- _posts/2018/05/2018-05-30-wistem-16.md
> posts/2018/05: Added interview 16 to linup WISTEM

- _posts/2018/05/2018-05-31-wistem-17.md
> posts/2018/05: Added interview 17 WISTEM

- _posts/2018/05/2018-05-31-wistem-17.md
> posts/2018/05: Small adjustment to interview 17 WISTEM

- openhours/README.md
> openhours: adjusted description for this week - episode 101

- go/wistem-2019/README.md
> go: Added preperation page for WISTEM 2019

- go/wistem-2018/README.md
- openhours/README.md
> go/wistem2018: Added button to countdown for WISTEM 2019

- openhours/about/README.md
- openhours/episodes/README.md
- Update to About sections
- Updates to episodes section
> OpenHours: Updates to OpenHours sections

- openhours/episodes/README.md
> openhours/episode: attempt to add embedded video small size

- openhours/episodes/README.md
> openhours/episodes: Added video links and split phases

- openhours/episodes/README.md
> openhours/episodes: Format fix

- openhours/about/README.md
- openhours/community/README.md
- openhours/impact/README.md
- Format fix to about page
- Filler content for community page, while leader board and bounty list (to-do repo) is being built out
- Added filler content to impact page while we develop timeline of important events
> OpenHours: Many format and filler changes

- _product/ce/hikey970/README.md
> product/ce/hikey970: Added link to lenovator purchase URL

- _product/ce/hikey970/README.md
> product/hikey970: Small fix to header matter

- _product/ce/hikey970/README.md
> product/ce/hikey970: Added aosp download link to sidebar

- openhours/README.md
> openhours: Update to weekly description for episode 102

- openhours/episodes/README.md
> openhours/episodes: Added more scheduled episodes to lineup

- openhours/episodes/README.md
> openhours/episodes: Added more content to table

- _product/ce/hikey970/README.md
- _product/mezzanine/secure96/README.md
- Fixed buy link for secure96 mezzanine
- Added amazon buy link for HiKey970
> Fixed various buy links for a couple boards

- _product/mezzanine/linkspritesensorkit/README.md
> product/mezzanine/linkspritekit: Attempt to fix broken link

- go/2018-partnership-brazil/README.md
> go/brazil-partnership-2018: Adjusted for this years collab

- index.html
> index.html: Added button for mezzanine/partner section of home page

- openhours/README.md
> openhour live link updated

- openhours/README.md
- openhours/episodes/README.md
- Description update
- episodes update
> openhours: updates for next week session

- _product/ce/hikey970/README.md
Signed-off-by: Jianguo Sun <sun_jianguo@hoperun.com>
> ce: hikey970: typo fix for buy-link of Amazon

- openhours/episodes/README.md
> openhours: Fixed episodes table with acurate info

- _product/mezzanine/arrow-nextbio/README.md
Added links to product brief and user guide on side bar
and within subject matter.
> product/mezzanine/arrow-nextbio: Added links for files

- _product/mezzanine/arrow-nextbio/README.md
> product/mezzanine/arrow-nextbio: Added link to documentation

- _product/mezzanine/arrow-nextbio/README.md
> products/mezzanine/arrow-nextbio: Small change to trigger build

- _product/mezzanine/arrow-nextbio/README.md
> product/mezzanine/arrow-nextbio: Attempt to fix broken links

- _product/mezzanine/arrow-nextbio/README.md
> product/mezzanine/arrow-nextbio: Adding link to documentation tab

- _product/mezzanine/arrow-nextbio/README.md
- _product/mezzanine/shiratech-lte/README.md
- LTE Shiratech mezzanine
- NextBio Mezzanine
> product/mezzanine: Attempt to add tab bar for multiple mezzanine

- _product/mezzanine/xinabox-b901/README.md
> product/mezzanine/xinabox-b901: Changed link to github

- _posts/2018/06/2018-06-29-openhours-ep104.md
> posts/2018/06: Added OpenHours ep 104 blog

- _posts/2017/01/2017-01-06-welcome-2017-year-96boards.md
> Attempt to fix broken link for website buildl

- openhours/README.md
- openhours/episodes/README.md
- Update calendar link
- Update description
- Update episode table and added to line up
> openhours: Updates for week 105

- services/README.md
- services/about/README.md
- services/partners/README.md
> Added new services folder with template content

- _data/sticky-tab-bar.yml
> data/sticky-tab-bar/yml: added services to lineup

- _posts/2018/07/2018-07-05-openhours-ep105.md
> posts/2018/07: Changed blog title for OpenHours ep 105

- _posts/2018/07/2018-07-05-openhours-ep105.md
> posts/2018/07: Fixed link to slideshow for ep105 blog

- _product/ce/bubblegum-96/README.md
> product/ce/bubblegum96: Added compliance download button to page

- openhours/README.md
> openhours: Updated description for episode 106

- _product/ce/dragonboard410c/README.md
- _product/ce/hikey/README.md
- _product/ce/hikey960/README.md
- _product/ce/mediatek-x20/README.md
- DragonBoard 410c
- Mediatk x20
- Hikey
- Hikey960
> Added compliance download button to several CE 96boards

- _product/ce/dragonboard410c/README.md
- _product/ce/dragonboard820c/README.md
- _product/ce/hikey960/README.md
- _product/ce/hikey970/README.md
- _product/ce/ultra96/README.md
> Changed format for tables

- services/README.md
> small change to services page

- _product/ce/ultra96/README.md
- x-ware as 3rd party image
- linux as primary os option
> product/ce/ultra96: Added x-ware and linux as OS options

- _product/ce/ultra96/README.md
> product/ce/ultra96: Attempt to fix broken link for OS download

- _posts/2018/07/2018-07-12-openhours-ep106.md
> posts/2018/07: Added OpenHours ep 106 blog

- _product/ce/ultra96/README.md
> product/ce/ultra96: Cleaned up side column

- _product/mezzanine/arrow-nextbio/README.md
- go/2018-partnership-brazil/README.md
- openhours/README.md
- openhours/episodes/README.md
- Additions to Brazil partnership "Go" page
- OpenHours: Updated description to episode 107
- OpenHours/episode: Updated table to include 105, 106 and 107 links
- OpenHours/episode: Added featured guest for episode on Oct 11th
- product/mezzanine/arrow-nextbio: Changed display image for NextBio Mezzanine
> openhours:product: Updates OpenHours and modifications to board page

- _posts/2016/06/2016-06-05-96boards-openhours-session-4-recap.md
> posts/2016/06: Removed broken link

- _data/routingrules.json
- _product/ce/dragonboard410c/README.md
- _product/ce/hikey/README.md
- _product/ce/hikey960/README.md
> family revamp: fixed broken links and added redirects to routingrules

- go/2018-ultra96-contest/README.md
> go: Added new go page for Ultra96 contest

- go/2018-partnership-brazil/README.md
- go/mezzanine-community/README.md
- Brazil Partnership program
- Mezzanine community
> go: Many changes to go pages

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Small changes and additions to go page

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Attempt to format and clean up page

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Small changes to cleanup go page

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Small change to trigger website built

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Further cleaning up of the page

- go/2018-ultra96-contest/README.md
> go/2018-ultr96-contest: Page cleanup

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: cleaning up formatting

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Small clean up

- _product/ce/dragonboard410c/README.md
> ce/db410c: Attempt to fix broken links

- go/2018-ultra96-contest/README.md
> go/2018-ultra96-contest: Small clean up commit

- go/2018-arm-contest/README.md
> go/2018-arm-contest: First content push

- go/2018-arm-contest/README.md
- go/2018-ultra96-contest/README.md
> go/2018-ultra96/arm-contest: Added button to both pages

- go/2018-arm-contest/README.md
> go/2018-arm-contest: Removed banners and added introduction paragraph

- go/2018-arm-contest/README.md
> go/2018-arm-contest: Small spelling fix and removed bottom banner

- go/2018-arm-contest/README.md
> go/2018-arm-contest: Removed unwanted link

- go/2018-arm-contest/README.md
> go/2018-arm-contest: Small typo fix

- go/2018-partnership-brazil/README.md
- Added videos playlists
- Adjusted content
> go/2018-partnership-brazil: Applied new formating for entire page

- openhours/README.md
> openhours: Updated content for episode 108

- openhours/episodes/README.md
> openhours/episode: Added latest reminder, and video link for last week

- _posts/2018/07/2018-07-19-openhours-ep107.md
> posts/2018/07: Added blog for OpenHours ep 107 with hello chava

- go/2018-ultra96-contest/README.md
> attempt to fix ultra96 contest go page

- _product/ce/hikey970/README.md
> hikey970: add links to LeMaker Debian and Ubuntu Images

- go/2018-partnership-brazil/README.md
This is to conform to other naming conventions for
other contests
> Changed permalink for Brazil partnership program

- _posts/2018/07/2018-07-26-openhours-ep108.md
> posts/2018/07: Added OpenHours ep 108 blog

- _posts/2018/07/2018-07-26-openhours-ep108.md
> go/2017/07: Attempt to fix broken links

- openhours/episodes/README.md
> openhours/episode: Added links for video ep 109 and reminder for 110

- _posts/2018/08/2018-08-08-audio-visualizer.md
> blog: db410c audio visualizer

- _posts/2018/07/2018-07-26-openhours-ep108.md
- _posts/2018/08/2018-08-02-openhours-ep109.md
> posts/2018/08: Added OpenHours ep 109 blog

- openhours/README.md
- openhours/episodes/README.md
- Update OpenHours description to 111
- Update table for episode 110 and 111
> openhours: Update from 110 to 111

- services/README.md
- services/partners/README.md
- Added Introduction to base service page
- Added format to page service page
- Added some draft content to partner page for Timsys
> services: Added format and some Timesys content to pages

- services/README.md
> services: Attempt to apply new format to page

- _product/ce/hikey/README.md
> product/ce/hikey: Added "more info" section to side bar

- _product/ce/hikey970/README.md
Removed misc section and replaced with Board specific
case and fan link.
> product/ce/hikey970: Added a case and fan to accessories section

- go/yvr18-shiratech-hackathon/README.md
> go page: shiratech hackathon at yvr18

- _data/members_db.yaml
- _posts/2016/11/2016-11-02-diy-drone-featuring-gumstix-96boards-take-flight-openhours.md
- _posts/2017/03/2017-03-28-96boards-96brews-automated-home-brewing.md
Witstek's website seems to be down so I have commented out temporarily
@kylekirkby the remainder of the broken links are from the jekyll repo, can you take a look?
> link fixes: misc link fixes

- go/yvr18-shiratech-hackathon/README.md
> go: correct link for shiratech hackathon

- _posts/2018/09/2018-09-05-mozilla-iot-1.md
> blog: mozilla iot pt 1

- go/2018-arrow-shiratech-hack/README.md
> go: Added new go page for Shiratech and Arrow hackathon

- go/2018-arrow-shiratech-hack/README.md
> go/2018-arrow-shiratech-hack: Small change to trigger website build

- go/2018-arrow-shiratech-hack/README.md
> go/2018-arrow-shiratech-hack: Update webpage with acurate information

- go/2018-arrow-shiratech-hack/README.md
> Small change to trigger website build

- go/2018-arrow-shiratech-hack/README.md
> Small changes to trigger website build

- _posts/2017/03/2017-03-28-96boards-96brews-automated-home-brewing.md
- _posts/2017/09/2017-09-21-openhours-ep71-aws-greengrass.md
> link fixes: removed old links to article that have long been deleted

- README.md
- _posts/2017/09/2017-09-21-openhours-ep71-aws-greengrass.md
> dummy pr to start builds

- openhours/README.md
> openhours: Update to episode 118 description and calendar link

- _product/accessories/power/README.md
> product/accessories/power: More changes to power section to test formatting

- _product/accessories/power/README.md
> product/accessories/power: Small change to product titles

- _product/ce/chameleon96/README.md
> product/ce/chameleon96: Changed purchase link and more info link

- openhours/README.md
- openhours/episodes/README.md
- Update description to episode 119 with Brandy Morgan of Creators Code
- Update episode table for current video and reminder links
- Update to landing page with proper calendar link
> OpenHours: Updated for episode 119 with Brandy Morgan`

- _posts/2018/10/2018-10-10-crypto-currency-register-part1.md
This commit fixes the Crypto Currency Regsiter - Part 1 blog to render
properly.
> blog: Fix Crypto Currency Regsiter - Part 1 blog

- _posts/2018/10/2018-10-14-ultra-96-PYNQ.md
> fixed image link in blog

- _posts/2018/10/2018-10-17-bubblegum96-mainlining-update-part-3.md
This commit adds Bubblegum96 Mainlining Update - Part 3 blog.
> blog: Add Bubblegum96 Mainlining Update - Part 3

- _posts/2018/10/2018-10-17-bubblegum96-mainlining-update-part-3.md
Fix subsection formatting for B96 mainlining update Part-3 blog.
> blog: Fix formatting for B96 mainlining update Part-3

- _posts/2017/03/2017-03-28-96boards-96brews-automated-home-brewing.md
- openhours/README.md
- openhours/episodes/README.md
> Website build, attempt to address broken links for website build

- openhours/README.md
Signed-Off-By: Theodore Grey <theodore.grey@linaro.org>
> openhours: small changes to README

- _product/mezzanine/shiratech-lte/README.md
> product/mezzanine/shiratech-lte: Attempt to get tabs added

- openhours/README.md
- openhours/episodes/README.md
> openhours: updates for episode 123

- _product/ce/sophon-edge/README.md
- Adjustment to size in spec table
- Added prices to purchase option
> product/ce/sophon-edge: Small updates to Sophon Edge page

- _posts/2018/11/2018-11-01-up-and-running-with-the-secure96-tpm.md
Added mention of Hoperun
Fixed Infineon feedback
Fixed links
> Updated blog post

- _posts/2018/11/2018-11-12-crypto-currency-register-part4.md
> Added Crypto blog, part 4

- openhours/README.md
> openhours: Update for episode 124

- services/partners/README.md
> services: Remove Archermind as service partner

- _posts/2018/11/2018-11-21-OpenHours-ep-124.md
> posts/2018/11: Added blog for OpenHours ep 124

- openhours/README.md
> openhours: Update to OpenHours episode 125

- _posts/2018/11/2018-11-22-interfacing-camera-with-rock960.md
This commit adds Camera interfacing with Rock960 blog.
> blog: Add Camera interfacing with Rock960

- openhours/README.md
> openhours: Update description for ep 125 with TRONBet

- _product/ie/wistrio/README.md
> ie/wistrio: Small fit in front matter for rendering

- _product/ie/wistrio/README.md
> product/ie/wistrio: Attempt to fix website rendering

- _product/mezzanine/shiratech-lte/README.md
> product/mezzanine/shiratech-lte: Added purchase link

- _product/ee/oxalis/README.md
> product/ee/oxalis: Attempt to render on website

- _product/ee/oxalis/README.md
> product/ee/oxalis: Attempt to fix website build

- _product/ee/oxalis/README.md
> product/ee/oxalis: Attempt to get board to render on website

- _product/ce/parrot/README.md
> product/ce/parrot: Add new purchase link

- openhours/README.md
> openhours: update openhours description to ep 126

- _product/ee/oxalis/README.md
> product/ee/oxalis: Some clarifications

- _product/ce/ultra96/README.md
> product/ce/ultra96: Added Chinese purchase link

- openhours/README.md
> openhours: update openhours for ep 127

- _product/mezzanine/tresor/README.md
> product/mezzanine/tresor: Fixed broken links to files

- _product/mezzanine/tresor/README.md
> product/mezzanine/tresor: Fixed title

- openhours/README.md
> openhours: update to OpenHours to episode 130

- openhours/README.md
> openhours: small formatting fix

- openhours/episodes/README.md
> openhours/episodes: Update table with new videos

- openhours/README.md
> openhours: Formatting fix

- _product/ce/sophon-edge/README.md
> product/ce/sophon-edge: Added links to source code

- _product/ce/ultra96/README.md
> product/ce/ultra96: Added "more" link to accessories section

- _product/ce/ultra96/README.md
> product/ultra96: attempt to fix broken link

- _product/ce/ultra96/README.md
Fixing link and adding "more" section to mezzanine table
> product/ce/ultra96: Attempt to fix broken link

- _product/ce/ultra96/README.md
> product/ce/ultra96: Adjustment to kits section

- _product/ce/ultra96/README.md
> link fix for ultra96 kit

- _product/ce/hikey970/README.md
- _product/ce/hikey970/ai.md
- _product/ce/rock960/README.md
- _product/ce/rock960/ai.md
Merging all previous PR's
- Fields have been nominally filled in and will need a more detailed description describing the Rock960's + HiKey970's features and highlighting their strong points
> Create AI tabs for HiKey970 + Rock960

- go/2019-arrow-campaign/README.md
> go: Added new go page for Arrow Campaign

- _product/ce/hikey970/ai.md
- _product/ce/rock960/README.md
- _product/ce/sophon-edge/ai.md
- _projects/template/REAMDE.md
Fixing "what's in the box" in hikey970/ai.md and sophon-edge/ai.md. Also small change to project template README and seed studio buy link for Rock960 README
> K1504296 patch 6

- _data/board-details.yml
Expansion Interface had 3 separate attribute tabs, merging them all under Expansion Interface
> Update board-details.yml Expansion Interface Attribute

- go/2019-arrow-campaign/README.md
> go/Arrow Campaign: Adding topics and changed permalink

- _product/mezzanine/tresor/README.md
> product/mezzanine/tresor: Fixed link

- _product/mezzanine/shiratech-nb1/README.md
> product/mezzanine/shiratech-nb1: Attempt to fix website build

- _product/mezzanine/shiratech-nb1/README.md
> product/mezzanine/shiratech-nb1: Fixed link

- _product/ce/dragonboard410c/README.md
- _product/ce/dragonboard820c/README.md
- _product/ce/hikey/README.md
> db410: db820: hikey: add Fedora as third party images

- openhours/README.md
> openhours: Updated OpenHours description to episode 134

- _product/ie/ivy5661/README.md
> product/ie/ivy5661: Attempt to fix broken rendering

- _product/ie/ivy5661/README.md
> product/ie/ivy5661: Small fix for rendering issue

- openhours/README.md
> openhours: Update description for ep 135

- openhours/README.md
> openhours: Small update to description for ep 135

- _product/mezzanine/shiratech-bosch/README.md
> product/mezzanine/shiratech-bosch: Relative link fix

- openhours/README.md
> openhours: Added a few links to openhours page

- _product/mezzanine/voice-ui/README.md
- Added new purchase link for Arrow
- Grammar fixes
> product/mezzanine/voice-ui: Small fixes

- _posts/2019/02/2019-02-20-fpga-mezz-lib-arduino.md
> blog: FPGA Mezzanine GPIO Library for Arduino Shields

- openhours/README.md
> openhours: update description and links for ep 137

- _product/mezzanine/voice-ui/README.md
Added link to Analog Devices under "More Info"
section.
> product/mezzanine/voice-ui: Added link

- _data/nav.yml
- pinout/lora_mezzanine_card_for_96board.html
Fixed Discord link in nav bar and swapped link
out of pinout section.
Signed-off-by: Robert Wolff
> Fixed a couple broken external links

- _posts/2017/08/2017-08-28-zephyr-i2c-update-for-carbon.md
- _product/mezzanine/shiratech-nb1/README.md
- Change title of Shiratech NB1 board on display page
- Fix a link in one blog
> Small fixes

- _product/mezzanine/tresor/README.md
> product/mezzanine: Attempt to fix build

- _data/sticky-tab-bar.yml
> link fixed for bubblegum96

- _product/ce/dragonboard845c/README.md
- Table adjustments
- Fixed broken forum link
> product/ce/dragonboard845c: Small clean up

- _product/ce/dragonboard845c/README.md
> Attempt to fix build

- _product/ce/dragonboard845c/README.md
> product/ce/dragonboard845c: URL change, test

- _product/ce/dragonboard845c/README.md
> product/ce/dragonboard845c: Fix link, attempt to fix table

- _product/ce/dragonboard845c/README.md
> product/ce/dragonboard845c: Fix link for build

- _product/ce/dragonboard845c/README.md
> product/ce/dragonboard845c: Attempt, link fix

- _product/ce/dragonboard845c/README.md
> product/ce/dragonboard845c: Attempt to fix broken link

- _product/ce/rb3-kit/README.md
> product/ce/rb3-kit: Remove link to Compliance

- openhours/README.md
> OpenHours ep 138 embedded world 2019 description update

- _product/ce/rb3-platform/README.md
> product/ce/rb3-platform: Adjustments to description + more

- _posts/2018/10/2018-10-26-hikey970-mainlining-update-part1.md
- _posts/2019/02/2019-02-28-hikey970-mainlining-update-part2.md
Add HiKey970 Mainlining Update - Part 2 blog
> blog: Add HiKey970 Mainlining Update - Part 2 blog

- openhours/README.md
> openhours: Update for OpenHours episode 141

- _product/ce/ultra96/README.md
> product/ce/ultra96: Adding v1 block to side panel

- openhours/README.md
> openhours: Update description to ep 142

- openhours/README.md
> openhours: Fix broken link

- openhours/README.md
> openhours: Attempt to fix broken link

- openhours/README.md
> openhours: Update to episode 143 description

- openhours/README.md
> openhours: Update calendar link for ep 142

- _product/ce/rb3-platform/README.md
> product/db845: Fixed broken links

- openhours/README.md
> openhours: Update for episode 143

- _product/mezzanine/aiva-96/README.md
> product/mezzanine: Fixed website rendering issue

- _layouts/product-display-page.html
Added side bar for Ultra96 v1 to layout
> layouts/product-display-page: Added new side bar

- _product/ce/ultra96/README.md
> product/ce/ultra96: Attempt to add new side bar

- _posts/2019/04/2019-04-26-openhours-ep144.md
> openhours: Add OpenHours ep 144 Blog

- _posts/2019/04/2019-04-26-sophon-edge-mainlining-update-part2.md
Add Sophon Edge Mainlining Update - Part 2 blog.
> blog: Add Sophon Edge Mainlining Update - Part 2

- openhours/README.md
> openhours: update for ep 145

- _posts/2019/04/2019-04-26-openhours-ep144.md
- openhours/README.md
- Update OpenHours for episode 146
- Fix blog date for rendering of post 144
> OpenHours and Blogs

- _posts/2019/05/2019-05-06-max7219-shiratech-fpga.md
> posts: Small typo fix

- _posts/2019/05/2019-05-02-openhours-ep145.md
- _posts/2019/05/2019-05-09-openhours-ep146.md
- Add OpenHours ep 145 Blog
- Add OpenHours ep 146 Blog
> posts/2019/05: Added two blogs

- _posts/2019/05/2019-05-02-openhours-ep145.md
- _posts/2019/05/2019-05-09-openhours-ep146.md
OpenHours ep 145 and 146 blog posts
> posts/2019/05: Fixed links on recent blog posts

- _go/96boards-india-initiative/README.md
- _posts/2017/12/2017-12-04-zephyr-hcsr04.md
- _posts/2017/12/2017-12-29-patient-monitoring-system-part1.md
- _posts/2018/01/2018-01-01-welcome-2018.md
- _posts/2018/10/2018-10-12-standardizing-96boards-support-in-zephyr.md
> posts:go: Link fixes for website build (internal and external)

- _data/sticky-tab-bar.yml
> ultra96v2 link fix

- _product/ie/4iot/README.md
> product/ie/4iot: Update purchase link

- _product/ie/4iot/README.md
> product/ie/4iot: Fixed description and link name

- _product/ce/sophon-edge/README.md
> product/ce/sophon-edge: Small fix to table

- openhours/README.md
> openhours: Update for episode 147

- _product/ce/ultra96/ai.md
> product/ce/ultra96: Fix broken AI page links

- _posts/2019/05/2019-05-20-path-libmraa-96boards-part-8.md
Add Our path to libmraa with 96Boards - Part 8 blog.
> blog: Add Our path to libmraa with 96Boards - Part 8

- _posts/2019/05/2019-05-14-maker-faire-p1.md
> posts/2019/05: Added p1 Maker Faire Blog

- openhours/README.md
> oh 148: wizeiot and aiva 96

- _posts/2019/05/2019-05-14-maker-faire-p1.md
> fix website build: removed link to missing thumbnail

- _posts/2019/05/2019-05-25-wistrio-cmake.md
> Blog: Add CMake support for 96Boards WisTrio blog

- openhours/README.md
> openhours: update for episode 149

- openhours/README.md
> openhours: Update for ep 151

- _includes/display-products.html
- _pages/specifications/README.md
> Fixed merge conflicts

- _pages/openhours/episodes/README.md
> openhours: Update to episodes tab

- _product/se/96boards-som-carrier-board/README.md
fixes links for: https://github.com/96boards/documentation/pull/812
> 96b-som-carrier: fixes link for doc pr

- _product/se/96boards-som-carrier-board/README.md
- _product/se/tb-96ai/README.md
- Added purchase link for RK3399 carrier board
- Added purchase link for AIoT SoM board
> product/se: Added purchase links for carrier and one som

- _product/se/tb-96ai/README.md
> product/se/ai: Added purchase link for alibaba

- _product/ce/ultra96/README.md
> product/ce/ultra96: Added actual order link from Avnet

- .gitignore
- _includes/members.html
- assets/css/app/custom.scss
- assets/css/app/overrides.scss
Updating padding for flow rows/members images
> Updating padding for flow rows/members images

- _posts/2019/05/2019-05-30-rb3-arm-intro.md
- _posts/2019/06/2019-06-17-rb3-arm-intro-opencv-1.md
- _posts/2019/07/2019-07-07-rb3-arm-opencv-threads.md
- _posts/2019/07/2019-07-10-rb3-opencv-gimme-code.md
- _posts/2019/07/2019-07-15-rb3-1080p-opencv.md
This PR contains 3 blogs
1: Multithreading on OpenCV.
2: RB3 opencv code walkthrough.
3: Streaming 1080p frames to opencv.
> blog: opencv series for rb3 project

- _projects/view/caffein-ai-tor/README.md
Signed-off-by: Julian Bartolone <julianbartolone@hotmail.com>
> Added category for caffein-ai-tor

- _posts/2019/05/2019-05-16-openhours-ep147.md
- _product/ee/developerbox/README.md
- Added new link for developerbox (Board only)
- Add OpenHours Blog ep147
> Small addition to developerbox and OpenHours

- _posts/2019/05/2019-05-23-openhours-ep148.md
> Add OpenHours ep 148 Blog

- _posts/2019/05/2019-05-30-openhours-ep149.md
> Added OpenHours ep 149 Blog

- _posts/2019/06/2019-06-06-openhours-ep150.md
> Add OpenHours Blog ep 150

- _posts/2019/07/2019-07-10-rb3-opencv-gimme-code.md
- _posts/2019/07/2019-07-15-rb3-1080p-opencv.md
Fixing markdown for python code blocks
> Fixing markdown for python code blocks

- _pages/membership/README.md
Remove `Issue 1.01 / Date February 9, 2016`
> Remove stale issue date

- _pages/openhours/README.md
> OpenHours ep 157 - Description and Cal Link

- _pages/openhours/README.md
> Small update to OpenHours page

- _data/settings.yml
> Fixing google analytics issue

- _pages/openhours/README.md
> Update description for OpenHours ep 158

- _pages/openhours/README.md
> Update description for OpenHours ep 159

- _go/san19/README.md
> Added SAN19 go page for UCSD community day

- _go/san19/README.md
> go/san19: Added hardware links and updated form

- _go/san19/README.md
> go/san19: Formatting

- _product/ce/rb3-platform/README.md
Signed-off-by: sgermanserrano <servando.german.serrano@linaro.org>
> Fixed db845 documentation link

- _go/san19/README.md
> Added some formatting

- _go/san19/README.md
> Format fixes and removal of some text

- _go/san19/README.md
> Made forum section longer on right side

- _product/ce/sophon-edge/README.md
> Added note regarding Sophon Edge compliance waivers

- _go/san19/README.md
> Added a bring your resume section

- _posts/2019/09/2019-09-09-rb3-its-alive.md
> blog: rb3: robotic arm pick and throw

- _posts/2019/09/2019-09-14-shiratech-fpga.md
> blog: Getting Started Resource - Shiratech FFPGA Mezzanine

- _pages/openhours/README.md
> openhours: Update description for ep 163

- _posts/2019/09/2019-09-21-db410c-quickstart.md
> blog: db410c quick start index

- _product/ee/poplar-hoperun/README.md
- _product/se/tb-96ai/README.md
- _product/se/tb-96aiot/README.md
A few website updates requested by Joyce Qi:
- Poplar buy link updated
- SoM Buy links updated and additional content/links aded
> Product Updates

- _data/universal-nav.yml
Added OpenAMP to universal nav
> Added OpenAMP to universal nav

- _data/sticky-tab-bar.yml
Added the rb3 robotics platform DragonBoard entry to sticky-tab-bar.yml
> Added the rb3 robotics platform DragonBoard entry to sticky-tab-bar.yml

- _posts/2019/10/2019-10-16-arduino-vs-pca9685.md
> blog: robotic arm: i2c update

- _pages/openhours/README.md
> update openhours page

- _product/ce/avenger96/README.md
> avenger96 fix price

- _pages/openhours/README.md
> openhours update

- _pages/openhours.md
> Openhours page updates

- _product/ce/hikey970/README.md
- _product/ce/rb3-platform/README.md
- _product/ce/rock960/README.md
- _product/ce/sophon-edge/README.md
- _product/ce/ultra96/README.md
- assets/json/ai_boards.json.html
Adding ai_boards.json output to enabled 96boards.ai to pull ai powered boards dynamically.
> Adding ai_boards.json output

- _product/ce/hikey970/README.md
- _product/ce/rb3-platform/README.md
- _product/ce/rock960/README.md
- _product/ce/sophon-edge/README.md
- _product/ce/ultra96/README.md
- assets/json/ai_boards.json.html
Adding short descriptions for 96boards ai products
> Adding short descriptions for 96boards ai products

- _pages/openhours.md
> openhours: update

- _product/ce/rock960/ai.md
- _product/mezzanine/secure96/README.md
- rock960 correct soc: fixes #981
- secure96 purchase link fix #325
Signed-off-by: Sahaj Sarup <sahajsarup@gmail.com>
> fixing stale issues

- _posts/2019/07/2019-07-10-rb3-opencv-gimme-code.md
- _posts/2019/07/2019-07-29-rb3-setup.md
- _posts/2019/08/2019-08-15-rb3-voice-vision.md
- _posts/2019/09/2019-09-09-rb3-its-alive.md
- _product/ce/hikey970/README.md
> Fixed some broken links

- _posts/2019/11/2019-11-08-hikey970-rt.md
Added links and Note for proper reproducibility 
> Corrections to blog

- _pages/openhours.md
- _product/mezzanine/3dtof/README.md
> openhours update and corrected 3dtof name.

- assets/css/app/custom.scss
Bold text fix - Setting the font-weight to 700 instead of 'bolder'
> Bold text fix - Setting the font-weight to 700 instead of 'bolder'

- _product/ce/dragonboard820c/README.md
> Updated board price

- _pages/openhours.md
- _posts/2019/12/2019-12-04-autoware.ai_hikey970.md
- _product/ce/dragonboard820c/README.md
- _product/mezzanine/3dtof/README.md
- assets/css/app/custom.scss
Develop->Master (content updates / bold text fix )
> Develop->Master (content updates / bold text fix )

- assets/css/app/custom.scss
Added sass style to ensure words are wrapped to new lines
> Added sass style to ensure words are wrapped to new lines

- _product/mezzanine/mipiadapter/README.md
> Mipi Adapter - Spaced words

- Gemfile
- robots.txt
This PR:
- Updates the `robots.txt`
- Adds the latest version of the theme
> Robots.txt fix 

- Gemfile
- robots.txt
Robots.txt fix / Added latest theme version #64 Develop->Master
> Robots.txt fix / Added latest theme version - Develop->Master

- _pages/about.md
Updating the flow front matter to fix missing overview text
> Updating the flow front matter to fix missing overview text

- _product/ee/akebi96/README.md
> akebi96: add board

- _product/ce/aiml/README.md
- _product/ce/thor96/README.md
> syntax fixes and removed unwanted links

- _pages/about.md
- admin/config.yml
Removing duplicate text YAML mapping key
> NetlifyCMS fixes - Removing duplicate text YAML mapping key

- _product/ce/avenger96/README.md
- _product/ce/dragonboard820c/README.md
- _product/ce/mediatek-x20/README.md
- _product/ce/parrot/README.md
- _product/ce/rb3-platform/README.md
- _product/ce/thor96/README.md
Fixing YAML issues seen in the Dev console for NetlifyCMS
> Fixing YAML issues seen in the Dev console for NetlifyCMS

- admin/config.yml
Updates to CMS based on the testing of adding a new product
> Updates to CMS based on the testing of adding a new product

- _includes/footer.html
- assets/css/app/custom.scss
Updated footer with revised contact links
> Updated footer with revised contact links

- build-site.sh
Added support for specifying a custom JEKYLL_PORT
> Added support for specifying a custom JEKYLL_PORT

- _product/ee/akebi96/README.md
> akebi96: fixed typo

- admin/config.yml
Added the display_attributes_table field
> Added the display_attributes_table field

- _product/ce/aiml/README.md
> aiml: updated price

- _posts/2020-02-14-diy-drones-digital.md
- _posts/2020-03-24-96boards-drone-project.md
> blog: add part3 of drone blog

- _posts/2020-05-20-aerocore2-upstreaming.md
> blog: aerocore2 zephyr

- _posts/2020-05-27-opengles3-panfrost-rock960.md
> blog: panfrost gles3 demo

- _product/ce/aiml/README.md
- _product/ce/thor96/README.md
- _product/se/tb-96ai/README.md
- _product/se/tb-96aiot/README.md
Adding ai_board: true to selected AI powered boards
> Adding ai_board: true to selected AI powered boards

- _posts/2020-05-20-aerocore2-upstreaming.md
- _posts/2020-05-27-opengles3-panfrost-rock960.md
- _product/ce/aiml/README.md
- _product/ce/thor96/README.md
- _product/se/tb-96ai/README.md
- _product/se/tb-96aiot/README.md
Adding ai_board: true flags to more AI Boards - blog post added  (develop->master)
> Adding ai_board: true flags to more AI Boards - blog post added  (develop->master)

- index.md
Adding Giveaway slide to homepage
> Adding Giveaway slide to homepage

- _data/members.json
> Member update for 31-07-20

- _posts/2020-08-07-arm_autonomy_pcu_1.md
> Added video

- _data/members.json
> Member update for 15-09-20

- _product/mezzanine/e-con-systems-camera/README.md
> mezzanine: e-con camera: update purchase link

- _data/members.json
> Member update for 21-10-20

- admin/config.yml
Removing references to staging.96boards.org
> Removing references to staging.96boards.org

- _product/ce/parrot/README.md
Corrected front matter on Parrot product page
> Corrected front matter on Parrot product page

- _data/members.json
> Member update for 23-06-21

- _data/members.json
> Member update for 27-07-21

- _data/members.json
> Member update for 15-02-22

- _product/ce/qualcomm-robotics-rb1/README.md
- _product/ce/qualcomm-robotics-rb2/README.md
The general description of RB1 and RB2 boards is somewhat disturbed, the issue is reported as https://github.com/96boards/website/issues/1425
> Fix formatting on RB1 and RB2 web pages
