96boards/website

96boards.org/Projects/ROSProductionUbuntuCore/README.md
This PR resolves #6 by adding the "ROS prototype to production on Ubuntu Core" series to the list of projects.
=> Add ROS prototype to production on Ubuntu Core series

_product/mezzanine/d3camera/README.md
I noticed the View/Download links on the Camera Mezzanine page were broken, so I fixed them! :D I haven't checked to see if the other links on other pages are also broken or not yet.
=> Fixes broken links to Camera Mezzanine datasheets.

_data/product_db.yaml
Changed front matter from Linux OS to Zephyr. Changed
description to reflect new one on nitrogen landing page.
=> Fixed product data for nitrogen

go/sfo17-connect-reach/README.md, openhours/README.md
Fixed some formatting issues in the SFO17 go page and added embedded link to
sign up form. Added the new description and calendar link to the OpenHours ep 67
page.
=> Fixed SFO17 go page and OpenHours update

_product/mezzanine/secure96/README.md
All occurance of OP-TEE has been removed from the README
for Secure96 Mezzanine
=> product/mezzanine/secure96: removed occurance of OP-TEE

openhours/README.md
+ Removed the div local countdown script
- @kylekirkby need to remove ccoundown js from the whole website
+ Added widget from countingdown.to https://w2.countingdownto.com/2050235
Signed-off-by: Shovan shovan@linaro.org
=> Change countdown to countingdown.to widget

_posts/2017/12/2017-12-01-et2017.md
The only thing changed in this PR is the title for the blog. From "Title" to "96Boards goes to Japan!"
=> posts/2017/12: Changed title to ET2017 Blog

go/2018-partnership-brazil/README.md, go/coursera-96support/README.md
These go pages will be worked on and eventually launched in the next few weeks.
- Coursera 96Support page will be launched within the next week
- Brazil Partnership page will be launched within next couple months.
Will add information to each page accordingly. Need official links for videos.
=> go: Added two new go pages

_posts/2018/01/2018-01-29-path-libmraa-96boards-part-6.md
This commit adds Path to Libmraa on 96Boards Part - 6 blog.
=> blog: Add Path to Libmraa on 96Boards Part - 6

_product/ee/poplar/README.md
* Remove claims about OS support from the hardware spec
* Replace RAM size with "up to 2G"
* Be less specific about the quantity of USB ports (for the various different board revs).
Fixes: https://github.com/96boards/website/issues/288
Signed-off-by: Daniel Thompson <daniel.thompson@linaro.org>
=> enterprise: poplar: Improve description of board

_product/ce/chameleon96/README.md, go/wistem-2018/README.md
- Fixed a typo in the Chameleon96 description on landing page
- Added more substance to go/wistem-2018 page
- Added schedule section with draft content
- Added greeting message to interview/form section
=> Small fix to chameleon96 and WISTEM go page

assets/js/package-all-products.js, assets/js/package-projects.js
Removed the Mailchimp JS include from the products/projects JS packages for a temporary fix to JQuery conflict issue.
=> Removed the Mailchimp JS include for a temporary fix to JQuery conflict issue.

openhours/README.md
now visitors can stream directly from OH page :)
=> openhours: add embedded youtube live stream

_product/ee/developerbox/README.md
I have been quite strict about spelling the board Developerbox (lowercase B)
in all the documentation. The reason for this is to discourage the view that
Developerbox is two words. Try searching for developer box" and "developerbox"
to see why!
Signed-off-by: Daniel Thompson <daniel.thompson@linaro.org>
=> developerbox: Adopt the same casing as the documentation

_product/mezzanine/xinabox-b901/README.md
Board page is not rendering. I think it has to do with
the header content being off. Small fix to test this.
=> product/mezzanine/xinabox-b901: Attempt to fix website rendering

_posts/2017/06/2017-06-01-googles-magenta-kernel-hikey-960.md, _product/ce/dragonboard820c/README.md
- 820c: add note for unsupported api and corrected cpu clock speed
- changed link to hikey960 target for zircon(previously magenta) kernel.
fixes #326
fixes #633
=> Fixes: 820c specs and Hikey960 link

go/2018-ultra96-contest/README.md
=> go/2018-ultra96-contest: Added button back on page for hackster.io site

go/2018-ultra96-contest/README.md
Waiting on update from Hackster.io to update workshop link
=> go/2018-ultra96-contest: Removed workshop link until further notice

services/README.md
Trying to take tab format from one of the product pages and applying it to the
services page. This might not work...
=> services: Attempt to add tabs to services page

_posts/2018/10/2018-10-12-standardizing-96boards-support-in-zephyr.md
This commit adds Standardizing 96Boards Support in Zephyr blog.
=> blog: Add Standardizing 96Boards Support in Zephyr blog

_product/ce/hikey960/README.md
The Aliexpress page no longer offers sales of the "raw" board at $239. It currently links to a reseller bundle that 96Boards have not agreed to provide purchasing links to. Remove this link.
Signed-off-by: Daniel Thompson <daniel.thompson@linaro.org>
=> hikey960: Remove aliexpress link

_data/nav.yml, _data/sticky-tab-bar.yml
- Removed OpenHours and Mezz Com from Projects Tab
- Added Initialives Tab with:
- OpenHours
- Women In STEM
- Mezzanine Community
- Pinout
=> added initiatives tab

_data/nav.yml
=> data/nav.yml: Swapped Slack for Discord link

_product/ce/dragonboard410c/README.md
Removed all occurrence of Snapdragon
from DB410c page. Replaced occurrences w/
APQ8016E.
=> Removed all occurrence of Snapdragon

_data/sticky-tab-bar.yml
Following links have been fixed
/documentation/enterprise/poplar-hoperun/additional-docs/index.html:
https://discuss.96boards.org/c/products/poplar-hoperun/ [404]
/documentation/enterprise/poplar-hoperun/build/index.html:
https://discuss.96boards.org/c/products/poplar-hoperun/ [404]
/documentation/enterprise/poplar-hoperun/getting-started/index.html:
https://discuss.96boards.org/c/products/poplar-hoperun/ [404]
/documentation/enterprise/poplar-hoperun/guides/index.html:
https://discuss.96boards.org/c/products/poplar-hoperun/ [404]
/documentation/enterprise/poplar-hoperun/hardware-docs/hw-user-manual.md.html:
https://discuss.96boards.org/c/products/poplar-hoperun/ [404]
/documentation/enterprise/poplar-hoperun/hardware-docs/index.html: …
=> link fixes

openhours/README.md
Ep 142 is canceled in preparation for
Live from Connect episode
=> openhours: update episode description for ep 142

_product/ce/ultra96/README.md
Slow transition to Ultra96 v2 content with v1
legacy side bar.
=> product/ce/ultra96: Various edits convert to v2

_product/ce/ultra96/README.md
With new family section of documentation
v1 and v2 docs have been split. Link needed
to be changed to accommodate said changes.
=> product/ce/ultra96: Change links for v1 and v2

_pages/openhours/README.md, _product/ce/avenger96/README.md
- Add purchase link for Avenger96
- Move Arrow Campaign link to "More Info" Section
- Update OpenHours calendar link
- Update OpenHours Description
=> Updates to Avenger96 and OpenHours

_product/ie/orangepi-i96/README.md
Some of the Download Options are not available anymore on the OrangePi Website.  Corrected it already in the Documentation and remove the non existing options from the Procuct Page as well, to not create confusion. 
Signed off by: Thore Krug opensource[at]thorekrug.de
=> Updated Download Section

assets/css/app/custom.scss
Simple CSS fix for plain markdown image includes. Images are not limited to the width of the main content container. However, images in blog posts should be added with the `image.html` include ensuring responsive images are generated. E.g
```
{% include image.html path="/assets/images/content/your-image.jpg" alt="An awesome image" %}
```
=> CSS fix for markdown images being too large

_data/universal_nav.yml
Removing Developer Cloud from Universal Navbar
=> Removing Developer Cloud from Universal Navbar
